Fix error caused by current module name lookup
```
  File ".../search/django/tasks.py", line 34, in ReindexMapReduceTask
    target = get_deferred_target()
  File ".../search/django/tasks.py", line 27, in get_deferred_target
    current_module = modules.get_current_version_name()
  File ".../google-cloud-sdk/platform/google_appengine/google/appengine/api/modules/modules.py", line 91, in get_current_version_name
    return os.environ['CURRENT_VERSION_ID'].split('.')[0]
  File ".../python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CURRENT_VERSION_ID'
```
Error when running dev server.